# =========================
# ConfigMap SonarQube
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  namespace: devops
data:
  SONAR_JDBC_URL: jdbc:postgresql://sonar-postgres.devops:5432/sonarqube

---
# =========================
# Secret SonarQube
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: devops
type: Opaque
data:
  SONAR_JDBC_USERNAME: c29uYXI=        # sonar
  SONAR_JDBC_PASSWORD: c29uYXI=        # sonar

---
# =========================
# PostgreSQL Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-postgres
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-postgres
  template:
    metadata:
      labels:
        app: sonar-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: sonarqube
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sonarqube-secret
                  key: SONAR_JDBC_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sonarqube-secret
                  key: SONAR_JDBC_PASSWORD

---
# =========================
# PostgreSQL Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: sonar-postgres
  namespace: devops
spec:
  selector:
    app: sonar-postgres
  ports:
    - port: 5432
      targetPort: 5432

---
# =========================
# SonarQube Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:9.9-community
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: sonarqube-config
            - secretRef:
                name: sonarqube-secret
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "2Gi"

---
# =========================
# SonarQube Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: sonarqube
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30090
