apiVersion: v1
kind: ConfigMap
metadata:
  name: student-management-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service.devops:3306/springdb?createDatabaseIfNotExist=true

---
apiVersion: v1
kind: Secret
metadata:
  name: student-management-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: "cm9vdA=="      # root
  SPRING_DATASOURCE_PASSWORD: "cm9vdDEyMw=="  # root123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: iheb1bouallagui/student-management:1.2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: student-management-config
            - secretRef:
                name: student-management-secret

---
apiVersion: v1
kind: Service
metadata:
  name: student-management-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
    - port: 8080        # port interne du service
      targetPort: 8080   # port du container
      nodePort: 30081    # port expos√© sur le noeud (valide pour Kubernetes)
